fix: replace cosmiconfig with simpler approach
honeybadger-io/honeybadger-js pull request #1267
Opened 2023-12-22 14:18 UTC by subzero10

## Status
**WIP**

## Description
Fixes: #1264
Replaces cosmiconfig with a simpler implementation.

## Todos
- [x] Remove cosmiconfig
- [x] Tests
- [ ] Update documentation

2023-12-22 14:20 UTC, subzero10 commented on CHANGELOG.md
Not necessary anymore since we release each package independently.

2023-12-22 14:48 UTC, stympy requested changes

2023-12-22 14:48 UTC, stympy commented on packages/js/examples/aws-lambda/handler.js
> +const shouldReport = (event) => {
I'd prefer the PR to only include the changes for cosmiconfig

2023-12-22 14:48 UTC, stympy commented on CHANGELOG.md
Did you really intend to drop the changelog?

2023-12-22 16:51 UTC, subzero10 commented on CHANGELOG.md
This is the root CHANGELOG file that used to be automatically generated when we had "fixed" versioning (all packages were synchronized on the same version). We switched to independent versioning a few months ago; therefore, this one is now outdated and unnecessary.

2023-12-22 16:53 UTC, subzero10 commented
FYI, integration tests are stuck, I will investigate.

2023-12-23 06:08 UTC, subzero10 commented on packages/js/examples/aws-lambda/handler.js
> +const shouldReport = (event) => {
Will close this one and create multiple PRs.

2023-12-23 06:08 UTC, closed without merging