Allow special characters in tags
honeybadger-io/honeybadger-js pull request #704
Opened 2022-02-16 01:12 UTC by joshuap

Also adds support for space-delimited tags; these strings are
equivalent:

- "one, two, three"
- "one two three"
- "one, two three"

This is a change I recently made to honeybadger-ruby (https://github.com/honeybadger-io/honeybadger-ruby/pull/422) and I realized we did the same thing here. I don't know why we were being so strict with the tag sanitizer, but I think this is better.

eslint also made some formatting changes, sorry about the noise.

2022-02-17 20:14 UTC, subzero10 requested changes

2022-02-17 20:14 UTC, subzero10 commented on src/core/client.ts
> +const TAG_SANITIZER = /\s/g
I don't think this is necessary anymore. If I'm thinking this correctly, by running the `TAG_SEPARATOR` first, there wouldn't be any individual tags with whitespace.

2022-02-17 20:14 UTC, subzero10 commented on src/core/client.ts
> +const TAG_SANITIZER = /\s/g
Update: To confirm my theory, I just tested removing usages of `TAG_SANITIZER` on this branch and all the tests pass.

2022-02-22 00:37 UTC, joshuap commented
Updated

2022-02-22 09:04 UTC, subzero10 approved these changes

2022-02-22 19:12 UTC, merged