feat: support non-error type "error.cause"
honeybadger-io/honeybadger-js pull request #945
Opened 2022-11-12 15:58 UTC by subzero10

## Status
**READY**

Closes: #934

## Description
Support non-error type `cause`.

2022-11-12 16:00 UTC, subzero10 commented on packages/js/test/unit/server/middleware.server.test.ts
> +        res.status(200).json({
`res.json` is deprecated, it should be `res.status().json()`

2022-11-12 16:10 UTC, subzero10 commented
@joshuap I modified the js library to send non-error type `cause` to the backend, but it seems that the Honeybadger web interface expects to render an Error object.

Here's how it looks when the `cause` object has `class`, `message` and `backtrace` properties:
<img width="1172" alt="Screenshot 2022-11-12 at 5 56 31 PM" src="https://user-images.githubusercontent.com/5813382/201483256-44ddddd7-31c3-49cc-9399-28a60ffee511.png">

And here's how it looks when the `cause` object is missing those properties:
<img width="1134" alt="Screenshot 2022-11-12 at 6 06 01 PM" src="https://user-images.githubusercontent.com/5813382/201483268-59716997-17b3-4166-b8b6-8d13e42647ff.png">
<img width="1147" alt="Screenshot 2022-11-12 at 6 05 53 PM" src="https://user-images.githubusercontent.com/5813382/201483263-d458bbab-8cfd-4eab-9ebb-2a890cec3b75.png">

2022-11-14 21:34 UTC, joshuap requested changes
> @joshuap I modified the js library to send non-error type `cause` to the backend, but it seems that the Honeybadger web interface expects to render an Error object.
> 
> Here's how it looks when the `cause` object has `class`, `message` and `backtrace` properties: <img alt="Screenshot 2022-11-12 at 5 56 31 PM" width="1172" src="https://user-images.githubusercontent.com/5813382/201483256-44ddddd7-31c3-49cc-9399-28a60ffee511.png">
> 
> And here's how it looks when the `cause` object is missing those properties: <img alt="Screenshot 2022-11-12 at 6 06 01 PM" width="1134" src="https://user-images.githubusercontent.com/5813382/201483268-59716997-17b3-4166-b8b6-8d13e42647ff.png"> <img alt="Screenshot 2022-11-12 at 6 05 53 PM" width="1147" src="https://user-images.githubusercontent.com/5813382/201483263-d458bbab-8cfd-4eab-9ebb-2a890cec3b75.png">

Yeah, a cause *is* an error in Honeybadger. That concept is an actual thing from Ruby and I think Java/some other languages have it as well. I don't really want to change the backend for causes to display non-error data. The best option for that sort of data is context. What you could do is let the user provide their own `Error` object (or potentially a `String` which would get coerced into an `Error` like we do in `Honeybadger.notify`):

```js
Honeybadger.notify(error, { cause: new Error('oh no') });

// and/or:

Honeybadger.notify(error, { cause: "oh no" });
```

Does that make sense?

2022-11-14 21:35 UTC, joshuap commented
Sorry, there should have been extra clarification on #934 before starting on it.

2022-11-14 21:36 UTC, joshuap commented
You could also ask if context would solve the use case in #934. If so, we could always skip this feature for now.

2022-11-17 18:23 UTC, shalvah approved these changes

2023-08-27 10:44 UTC, subzero10 commented
Closing because of inactivity. We may come back to this again.

2023-08-27 10:44 UTC, closed without merging